export const actionTypes = {
    SET_CURRENT_CARDS_DATA: 'SET_CURRENT_CARDS_DATA',
    SET_DISTRIBUTED_CARDS_DATA: 'SET_DISTRIBUTED_CARDS_DATA',
    SET_DEALT_CARDS_DATA: 'SET_DEALT_CARDS_DATA',
    SET_DEAL_WINNING_CARD: 'SET_DEAL_WINNING_CARD',
    SET_DEAL_WINNING_PLAYER: 'SET_DEAL_WINNING_PLAYER',
    SET_DEALT_PROPERTY: 'SET_DEALT_PROPERTY',
    SET_FINAL_WINNER: 'SET_FINAL_WINNER',
}